/*
 Network Stack for PSoC3-ENC28J60 hardware
 -----------------------------------------
 Title  : Webserver functions.
 Author : Kartik Mankad
 Date : 30-06-12
 This code is licensed as CC-BY-SA 3.0
 Description : Webserver functionality that allows the PSoC to serve dynamic text/html webpages.
*/

#include "IPStackMain.h"
#include <string.h>
#include <stdio.h>


unsigned int WebServer_ProcessRequest(TCPhdr* TCPPackData){
    unsigned int datalen;
    
    unsigned int temp;/*Variable to store the Die Temperature*/
    unsigned char templine[40];/*To store the temperature message*/
    
    
    if (strncmp("GET ",(unsigned char*)TCPPackData+sizeof(TCPhdr),4)!=0){
        //Reply with a 200 OK with queries that arent of type GET.
        //
        // for possible HTTP Status codes(404,301 etc) see:
        // http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html
        datalen=AddWebServerData(TCPPackData,0,"HTTP/1.0 200 OK\r\nContent-Type: text/html\r\n\r\n");
    }
    
    
    /*Get the temperature*/
    DieTemp_GetTemp((int16*)&temp);
    
    /*Format the temperature into a good string*/
    sprintf(templine,"<h2>PSoC Temperature is %d deg C</h2>",temp);
    
    
    /*Build HomePage*/
    if (strncmp("/ ",(unsigned char*)TCPPackData+sizeof(TCPhdr)+4,2)==0){
        datalen=AddWebServerData(TCPPackData,0,"HTTP/1.1 200 OK\r\nContent-Type: text/html\r\n\r\n");
        datalen=AddWebServerData(TCPPackData,datalen,"<title>ENC28J60-PSoC3</title>");
        datalen=AddWebServerData(TCPPackData,datalen,"<h1>ENC28J60-PSoC3</h1>");
        datalen=AddWebServerData(TCPPackData,datalen,"<hr>");
        datalen=AddWebServerData(TCPPackData,datalen,templine);
    }else{
		datalen=AddWebServerData(TCPPackData,0,"HTTP/1.1 401 Unauthorized\r\nContent-Type: text/html\r\n\r\n<h1>401 Unauthorized</h1>");
	}
    
    
    /*Deliver the webpage*/
    return(ReplyTCP_Webserver(TCPPackData,datalen));
}

/*******************************************************************************
* Function Name: AddWebServerData
********************************************************************************
* Summary:
*   This function is used to append webpage data to the outgoing reply
*   to the GET query.
*   
* Parameters:
*    TCPPkt - pointer to a TCP packet that has the GET Query.
*    pos  - position in the data part where data must be appended.
*    str - the constant string that is to be appened.This is usually the HTML.
* Returns:
*   current position of data in the TCP packet.
*******************************************************************************/
unsigned int AddWebServerData(TCPhdr* TCPPkt,unsigned int pos,const char* str){
    while(*str){
        *((unsigned char*)TCPPkt+sizeof(TCPhdr)+pos)=*str;
        pos++;
        str++;
    }
    return(pos);
}

/*******************************************************************************
* Function Name: ReplyTCP_Webserver
********************************************************************************
* Summary:
*   This is used to send the webpage generated by AddWebServerData,in response
*   to the GET query.This function ACK's the GET query,and then sends the reply.
*   
* Parameters:
*    TCPPkt - pointer to a TCP packet that has the Webpage.
*    len  - length of this packet.
* Returns:
*   TRUE(0)- if the packet was successfully sent.
*   FALSE(1) - if the packet was not successful in transmission.
*******************************************************************************/
unsigned int ReplyTCP_Webserver(TCPhdr* TCPPkt,unsigned int datlen){
    
    /*Send an ACK for the GET query*/
    ackTcp(TCPPkt,(TCPPkt->ip.len)+14,0,0,0,0);
    
    /*Based on that ACK we sent,create the reply to the GET query*/
    /*Set the flags.*/
    TCPPkt->ACK=1;
    TCPPkt->PSH=1;
    TCPPkt->FIN=1;
    
    /*Set the length field*/
    TCPPkt->ip.len=(sizeof(TCPhdr)+datlen)-sizeof(EtherNetII);
    
    /*Zero out and then compute IP checksum*/
    TCPPkt->ip.chksum=0x00;
    TCPPkt->ip.chksum=checksum((unsigned char*)TCPPkt + sizeof(EtherNetII),sizeof(IPhdr)-sizeof(EtherNetII),0);
    
    /*Zero out and then compute TCP checksum*/
    TCPPkt->chksum=0x00;
    TCPPkt->chksum=checksum((unsigned char*)TCPPkt->ip.source,0x08+0x14+datlen,2);
    
    /*Send the reply*/
    return(MACWrite((unsigned char*)TCPPkt,sizeof(TCPhdr)+datlen)); 
 }

/* [] END OF FILE */
